/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Question = IDL.Record({
  'id' : IDL.Nat,
  'topic' : IDL.Text,
  'subject' : IDL.Text,
  'correctIndex' : IDL.Nat,
  'questionText' : IDL.Text,
  'options' : IDL.Vec(IDL.Text),
});
export const Alarm = IDL.Record({
  'id' : IDL.Nat,
  'subject' : IDL.Text,
  'enabled' : IDL.Bool,
  'alarmLabel' : IDL.Text,
  'timeMinutes' : IDL.Nat,
  'timeHours' : IDL.Nat,
});

export const idlService = IDL.Service({
  'createAlarm' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'deleteAlarm' : IDL.Func([IDL.Nat], [], []),
  'getRandomQuestion' : IDL.Func([IDL.Text], [IDL.Opt(Question)], ['query']),
  'getStats' : IDL.Func([], [IDL.Nat, IDL.Float64], ['query']),
  'listAlarms' : IDL.Func([], [IDL.Vec(Alarm)], ['query']),
  'recordDismiss' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'updateAlarm' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text, IDL.Text, IDL.Bool],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Question = IDL.Record({
    'id' : IDL.Nat,
    'topic' : IDL.Text,
    'subject' : IDL.Text,
    'correctIndex' : IDL.Nat,
    'questionText' : IDL.Text,
    'options' : IDL.Vec(IDL.Text),
  });
  const Alarm = IDL.Record({
    'id' : IDL.Nat,
    'subject' : IDL.Text,
    'enabled' : IDL.Bool,
    'alarmLabel' : IDL.Text,
    'timeMinutes' : IDL.Nat,
    'timeHours' : IDL.Nat,
  });
  
  return IDL.Service({
    'createAlarm' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'deleteAlarm' : IDL.Func([IDL.Nat], [], []),
    'getRandomQuestion' : IDL.Func([IDL.Text], [IDL.Opt(Question)], ['query']),
    'getStats' : IDL.Func([], [IDL.Nat, IDL.Float64], ['query']),
    'listAlarms' : IDL.Func([], [IDL.Vec(Alarm)], ['query']),
    'recordDismiss' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'updateAlarm' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text, IDL.Text, IDL.Bool],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };