/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Alarm {
  'id' : bigint,
  'subject' : string,
  'enabled' : boolean,
  'alarmLabel' : string,
  'timeMinutes' : bigint,
  'timeHours' : bigint,
}
export interface Question {
  'id' : bigint,
  'topic' : string,
  'subject' : string,
  'correctIndex' : bigint,
  'questionText' : string,
  'options' : Array<string>,
}
export interface _SERVICE {
  'createAlarm' : ActorMethod<[bigint, bigint, string, string], bigint>,
  'deleteAlarm' : ActorMethod<[bigint], undefined>,
  'getRandomQuestion' : ActorMethod<[string], [] | [Question]>,
  'getStats' : ActorMethod<[], [bigint, number]>,
  'listAlarms' : ActorMethod<[], Array<Alarm>>,
  'recordDismiss' : ActorMethod<[bigint, bigint], undefined>,
  'updateAlarm' : ActorMethod<
    [bigint, bigint, bigint, string, string, boolean],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];